### ISSUE TITLE
Line numbers are almost invisible

### ISSUE THREAD

**Issue by d86leader** [ulwlu/elly.vim#12]
![Screenshot_20201213_200455](https://user-images.githubusercontent.com/6142210/102012711-9a5ea680-3d7e-11eb-9470-61bc9d12c7e9.png)

I'm using neovim inside konsole

**Comment by ulwlu** [comment]
@d86leader 
Thank you for reporting, yes as I see you are right.
What do you think right one? It will be more obvious.

If you have an other opinion, I'd like to hear.

<img width="724" alt="ss 1" src="https://user-images.githubusercontent.com/41639488/102012844-e8c87100-3d8f-11eb-8dfe-cfae59d4661e.png">

**Comment by d86leader** [comment]
I personally would like it a little brighter still, maybe a bit dimmer than the comments on the left? But I don't know anything about choosing colors. (=

**Comment by ulwlu** [comment]
Umm I see, it makes sense.
Just a minute, I/m gonna adjust this more.

**Comment by ulwlu** [comment]
@d86leader 
Hi. I update the highlight for first trying.

https://github.com/ulwlu/elly.vim/pull/14

Would you update and check?

**Comment by d86leader** [comment]
@ulwlu I've updated and checked, and it's certainly better, the numbers are legible now

**Comment by ulwlu** [comment]
Thank you for checking!

## refs for someone in the future who finds this issue
If you feel like to change a bit more highlight, please use below command in your vimrc. It will overwrite the highlight with your preferable color.

```vim
highlight LineNr guifg=#2c4350
```
