### ISSUE TITLE
not an isse

### ISSUE THREAD

**Issue by pjhalsli** [ulwlu/elly.vim#15]
this is not an issue - I'd rather take this opportunity for expressing my gratitude for this great scheme. I have termie them colors . Vim colors obs - also rofi and polybar follows the same color scheme. I installed gtk- framework to create a gtk theme that follows the same colors. Consistency is so underrated. Anyway - if I'm to guess I think elly will be my new theme for at least 8-12 months. so pleasant to look at hour after hour - very underrated IMHO
Really hoping more ppl discover this great colors
Anyways - THANK YOU

**Comment by ulwlu** [comment]
OMG, you really moved me. I'm truly glad to hear that!
Thank you very much for finding and using!

**Comment by ulwlu** [comment]
@pjhalsli 
Hi, I just came up to think, but may I add ref links in README if you have these repository?

> also rofi and polybar follows the same color scheme

I am not linux user, but it could be awesome to see something fits to elly theme as many as possible.
I look forward to hearing from you.
