### ISSUE TITLE
[COLORS][BUG] on colorscheme after successful installation

### ISSUE THREAD

**Issue by Turodoras** [ulwlu/elly.vim#17]
Hey,

First of all THANK YOU a LOT for everything you've done. Your work is AMAZING. I've spent the last 24 hours trying to customize my entire i3 / zsh / urxvt config files to fit your orange mac theme:

<img width="1440" alt="orangemac" src="https://user-images.githubusercontent.com/44328278/102146374-19300e00-3e69-11eb-861d-e5f4cb78e245.png">

And I feel really good about what I've done so far.

The thing is, you did not upload you config files for this one and I'm trying to adapt the `elly` theme to achieve my goal but the whole colorsheme seems broken.

I use VIM 8.2 and I installed the plugin via Vundle as shown below:

```
Plugin 'ulwlu/elly.vim' " Theme: https://github.com/ulwlu/elly.vim
...
set termguicolors                                                               
colorscheme elly
```

And this is what I get as a result:

![2020-12-15-000326_1906x1044_scrot png](https://user-images.githubusercontent.com/44328278/102147051-62349200-3e6a-11eb-9c36-65e9f2d94ddf.png)

On the right you can see everything only has one color, and I get the same result with the `abyss` theme (with that same red color but some line are white too...)

Here is an other screenshot:

![2020-12-15-000549_951x1045_scrot](https://user-images.githubusercontent.com/44328278/102147059-6660af80-3e6a-11eb-81c0-fd02dab397f0.png)

I am very sorry if I've done something wrong during the installation, I really rode the `README.md` a 100 times to be sure I'm not bothering you for a mistake on my own.

Thank's!

**Comment by ulwlu** [comment]
@Turodoras 
Thank you for reporting!

>The thing is, you did not upload you config files for this one

...and sorry I think I already deleted that theme...thinking recovering it when I have a time.

> On the right you can see everything only has one color, and I get the same result with the abyss theme (with that same red color but some line are white too...)

This one is interesting.
Could you upload your whole vimrc?

**Comment by Turodoras** [comment]
Sure, here it goes:

```python
" ~/.vimrc

"" ---------------------
"        PLUGINS
"" ---------------------

" Vundle is for plugin installation
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'ntpeters/vim-better-whitespace' " Remove useless spaces
Plugin 'vim-airline/vim-airline' " Colors on bottom bar
Plugin 'vim-airline/vim-airline-themes' " Theme for vim-airline
Plugin 'suan/vim-instant-markdown', {'rtp': 'after'} " Markdown visualisation

" Theme
Plugin 'ulwlu/elly.vim' " Theme: https://github.com/ulwlu/elly.vim
Plugin 'ulwlu/abyss.vim' " Theme: https://github.com/ulwlu/abyss.vim

" MUST BE AFTER PLUGINS
call vundle#end()
filetype plugin indent on

" Options
set t_Co=256 " Set vim to support 256 colors
let g:airline_theme='elly' " Which theme for the bottom bar

" Instant markdown options - uncomment to override defaults:
let g:instant_markdown_slow = 1
"let g:instant_markdown_autostart = 0
"let g:instant_markdown_open_to_the_world = 1
"let g:instant_markdown_allow_unsafe_content = 1
"let g:instant_markdown_allow_external_content = 0
"let g:instant_markdown_mathjax = 1
"let g:instant_markdown_logfile = '/tmp/instant_markdown.log'
"let g:instant_markdown_autoscroll = 0
"let g:instant_markdown_port = 8888
let g:instant_markdown_python = 1

"" ---------------------
"       PARAMETERS
"" ---------------------

" Theme
set termguicolors
colorscheme elly

set encoding=utf-8

syntax on
set number " Line numbers
set cc=80 " Red column

set showbreak=+++
set showmatch
set list listchars=tab:>-,trail:-

set hlsearch
set smartcase
set ignorecase
set incsearch

set autoindent
set cindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

set ruler

set undolevels=1000
set backspace=indent,eol,start

"" ---------------------
"       FUNCTIONS
"" ---------------------

" toggle between number and relativenumber
function! ToggleNumber()
    if(&relativenumber == 1)
        set norelativenumber
        set number
    else
        set relativenumber
    endif
endfunc

"" ---------------------
"       REMAPPING
"" ---------------------

" Save
map <F3> :w <CR>
" Quit and save
map <F4> :x <CR>
" Remove all trailling space
map <F6> :StripWhitespace <CR>
" Reindent all the file
map <F7> gg=G <CR>
" Quit without saving
map <F8> :q! <CR>
" Launch the plugin install
map <F9> :PluginInstall <CR>
" Switch between relative number and absolute number
map <F10> :call ToggleNumber() <CR>
```

I'm really scared I did something stupid lol

**Comment by ulwlu** [comment]
Thank you! I'm gonna look into it.

Currently I'm in Japan and my job is going to start now, so will return you maybe in 12 hours.

**Comment by ulwlu** [comment]
@Turodoras 
Just a quick response.
It works as expected, can't reproduce a bug.

Therefore, maybe there is an another cause outside vim.
It interests me, so I look for that cause.

<img width="649" alt="ss 1" src="https://user-images.githubusercontent.com/41639488/102151286-e06a5600-3eb5-11eb-8c32-5bf8c51530db.png">

**Comment by Turodoras** [comment]
Erf I'll try to dig it out then, thank's a lot for the quick response and have a nice day, I'm going to sleep (2 AM here ahah).

I'll keep you updated if this evolves for sure!

**Comment by Turodoras** [comment]
Managed to fix it, for some reason all I had to do was removing the `set termguicolors` line (found on [stackoverflow](https://stackoverflow.com/questions/41482516/colorscheme-for-vim-works-on-termite-and-not-on-urxvt)).

Thank's for your time anyway, keep up that crazy work!

**Comment by ulwlu** [comment]
Have a good night! Thank you very much.

-- p.s.

I found out that I needed to support 16-colors terminals such as **urxvt** like your terminal.
Left is 256colors, and right is 16colors. It apparently lacks of colors.

<img width="1072" alt="ss 3" src="https://user-images.githubusercontent.com/41639488/102153565-d8f97b80-3eba-11eb-8455-2f82c9ff03e1.png">

I found solarized is supporting, so gonna fix with this ref.

https://github.com/altercation/solarized/blob/master/vim-colors-solarized/colors/solarized.vim#L283-L300

**Comment by ulwlu** [comment]
> Managed to fix it, for some reason all I had to do was removing the set termguicolors line (found on stackoverflow).

Oh! I didn't know that.
But it seems that it becomes different colors.

I felt relieved, but I'm going to keep trying with 16bit colors terminal as well.

**Comment by Turodoras** [comment]
Yes I just realized the lack of colors. That would be awesome indeed. Quick question, why is `urxvt` 16-colors here and when I type `echo $TERM` I do have `rxvt-unicode-256color` as output? Isn't `urxvt` supposed to handle 256 colors?

**Comment by ulwlu** [comment]
I maybe said wrong, but still not sure.
It would be compatible if I set like guifg=256 anyway.

Sorry I was not so familiar with these type of terminal, it still takes time to resolve...

**Comment by Turodoras** [comment]
How are you sorry lol, thank's for taking this time, I'm still very new to this whole ricing world

**Comment by ulwlu** [comment]
@Ewael@really sorry to be late, but now I adapt elly.vim with cterm terminal such as urxvt or mac terminal.

You can see by setting 'let g:elly_termmode="cterm"' before 'colorscheme elly'.

It doesn't look like a thumbnail since cterm lacks of colors, thought. I tried my best to reproduce.

**Comment by Ewael** [comment]
@ulwlu Sorry I was drowning under work too, but thank's A LOT mate, doesnt matter if it's not perfect, really means a lot that you took this time, appreciate it
