### ISSUE TITLE
Error color visibility

### ISSUE THREAD

**Issue by charlyalizadeh** [ulwlu/elly.vim#2]
![error_elly](https://user-images.githubusercontent.com/49985859/98160153-12af8d80-1ede-11eb-9cde-c82197fa35ba.png)
I have an error with the background colour of errors. For information this a C++ source file using [ale](https://github.com/dense-analysis/ale) for linting.

Edit :

**Comment by ryuta69** [comment]
Oh I see, I think I need to apply some syntax in ale plugin.
Gonna fix this in few days.

Thank you for your report.

**Comment by charlyalizadeh** [comment]
Thank you !

**Comment by ryuta69** [comment]
Oh sorry, I closed by mistake.
@charlyalizadeh 

https://github.com/ryuta69/elly.vim/pull/4

I applied some ale syntax. You can see the fix after updating elly.vim.

I am not sure if this is suitable syntax, so would love to hear your opinion.

<img width="104" alt="ss 2" src="https://user-images.githubusercontent.com/41639488/98272242-36ed9600-1fd4-11eb-8b71-b736b2ef9f4a.png">

<img width="119" alt="ss 1" src="https://user-images.githubusercontent.com/41639488/98272238-35bc6900-1fd4-11eb-90c7-f4bc46b5b1aa.png">

**Comment by ulwlu** [comment]
@charlyalizadeh 
Hi, hopefully you'll notice this reply again.

P.S.
I found you posted this on Reddit! It's a masterpiece and beyond my expectation!!
https://www.reddit.com/r/unixporn/comments/jzrixh/bspwm_i_finally_found_the_perfect_colorscheme/
