### ISSUE TITLE
ANSI color code 08 becomes invisible

### ISSUE THREAD

**Issue by atusy** [ulwlu/elly.vim#24]
On `:term`, I tried following code and found that `08` is invisible.
Is this intentional?

```
for ((i = 0; i < 16; i++)); do
    for ((j = 0; j < 16; j++)); do
        hex=$(($i*16 + $j))
        printf '\e[38;5;%dm0x%02X\e[m ' $hex $hex
    done
    echo "";
done
```

![image](https://user-images.githubusercontent.com/30277794/161485073-32f58b48-8112-48b3-9c18-2b1c61418621.png)

**Comment by ulwlu** [comment]
@atusy thank you for catching. it actually was not on purpose. could you update elly.vim and check it again?

<img width="698" alt="ss 0004-04-04 at 19 31 21" src="https://user-images.githubusercontent.com/41639488/161526205-912ed27f-f202-4366-91f2-06c2fbe7a859.png">

**Comment by atusy** [comment]
Thank you for quick action! Looks great!!
