### ISSUE TITLE
Red #340001 is almost invisible on the #111a1f background

### ISSUE THREAD

**Issue by m-kru** [ulwlu/elly.vim#5]
![image](https://user-images.githubusercontent.com/26227737/100103276-f65f9a80-2e64-11eb-8285-068da30251b5.png)

**Comment by m-kru** [comment]
Ok, this value is on the screenshot, the file has #810002 for red.

**Comment by ulwlu** [comment]
Hi @m-kru, thank you for reporting a issue.

To solve this, I'd like to know what makes this color.
Is that highlighted by plugin or your vimrc?

That seems an original syntax highlighting, so I need to overwrite that with other color code such as #810002.

**Comment by ulwlu** [comment]
Oh, gets closed at same time I commented.
