### ISSUE TITLE
ALE - issue highlighting appears messed up

### ISSUE THREAD

**Issue by jezus-nunez** [ulwlu/elly.vim#7]
Not much to tell here, this is how it looks:
![image](https://user-images.githubusercontent.com/48286720/101039338-1c2f2280-357c-11eb-836b-7a0e6fd0ac6e.png)

I don't think that the outcome of the command you left will serve much, but leaving it here just in case
![image](https://user-images.githubusercontent.com/48286720/101040337-64e6db80-357c-11eb-884f-360c040854a4.png)

Great color scheme, by the way 👍

**Comment by ulwlu** [comment]
@jezus-nunez 
Thank you for your report!

Oh sorry, it's my mistake. I made error/warning line's bg to be colored by this PR.
https://github.com/ulwlu/elly.vim/pull/4/files

I'm going to fix now.

>Great color scheme, by the way 👍

Thank you very much!

**Comment by ulwlu** [comment]
@jezus-nunez 

Hi, would you kindly tell me if the syntax below looks fine?

<img alt="ss 5" src="https://user-images.githubusercontent.com/41639488/101050482-ca13ee80-35c7-11eb-94e8-a131d8d2d95d.png">

* note: Underline actually is supposed to be **undercurled** (I set so), but I'm using iTerm2 so it doesn't display as curled. Ref: https://gitlab.com/gnachman/iterm2/-/issues/6382

**Comment by jezus-nunez** [comment]
Looks good mate 👍 thank you for the prompt fix!!
