### ISSUE TITLE
different colors in nvim terminal

### ISSUE THREAD

**Issue by pjhalsli** [ulwlu/elly.vim#9]
As I posted on Reddit the color scheme changes if you use the terminal in nvim
https://imgur.com/a/JMknOUB
Not sure why that happens - but you can clearly see the scheme changes-wanted to notify you of the issue. As you can see also the dir colors change color

**Comment by ulwlu** [comment]
@pjhalsli 
Hi, Thank you for reporting a issue!

Yeah after you mentioned on reddit, I looked into and found this issue.
https://github.com/neovim/neovim/issues/7238

Maybe I need to fix some syntax highlight. I'll notify you when I fix this.

**Comment by ulwlu** [comment]
@pjhalsli 
Hi! I fixed here https://github.com/ulwlu/elly.vim/pull/10, like below.

Would you update by `:PlugUpdate` and confirm it's fixed when you have time?

<img width="1330" alt="ss 1" src="https://user-images.githubusercontent.com/41639488/101279832-61678480-3808-11eb-81a5-015b0180e47b.png">

**Comment by pjhalsli** [comment]
perfect - thank you.  I'll close this issue now
